### ISSUE TITLE
Nonexisting include files, failure to detect compiler version

### ISSUE THREAD

**Issue by ltning** [freebsd/drm-kmod#443]
Since "recently", drm-kmod will not build on 15-stable. I believe at least one of the offending commits is 09104ee98fab275eb7bd5913a3a6288ef6b55e4b which causes invalid flags to be used with base LLVM (which is version 19-something).

The other one I have no iea of: `/usr/src/sys/sys/vnode.h` attempts to include a `vnode_if.h` which cannot be found:

```
In file included from /root/drm-kmod/drivers/gpu/drm/drm_atomic.c:30:
In file included from /root/drm-kmod/linuxkpi/gplv2/include/linux/sync_file.h:18:
In file included from /usr/src/sys/compat/linuxkpi/common/include/linux/list.h:48:
/usr/src/sys/sys/vnode.h:625:10: fatal error: 'vnode_if.h' file not found
```

Kernel and world are freshly built and installed, currently 771a65210018c68198ea413df10225e87a0ea909 in stable/15).

**Comment by dumbbell** [comment]
Fixed by #445.
